#############################################################################
# Makefile for building: Daigaku
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  Daigaku.pro
# Template: app
# Command: C:\Qt\Static\5.13.0_Static\bin\qmake.exe -o Makefile Daigaku.pro -spec win32-g++ "CONFIG+=release" "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\Static\5.13.0_Static\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\Static\5.13.0_Static\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\Static\5.13.0_Static\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Daigaku.pro ../../../../Qt/Static/5.13.0_Static/mkspecs/win32-g++/qmake.conf ../../../../Qt/Static/5.13.0_Static/mkspecs/features/spec_pre.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/qdevice.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/device_config.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/sanitize.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/gcc-base.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/g++-base.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/angle.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/windows-vulkan.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/g++-win32.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/common/windows-desktop.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/qconfig.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_winextras.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_dsengine.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qdirect2d.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qgif.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qicns.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qico.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtga.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwebgl.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwebp.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_scene2d.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_xinputgamepad.pri \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/qt_functions.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/qt_config.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/toolchain.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/default_pre.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/resolve_config.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/default_post.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/resources.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/qtquickcompiler.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/precompile_header.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/warn_on.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/qt.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/gc_binaries.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/moc.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/opengl.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/qmake_use.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/file_copies.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/windows.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/testcase_targets.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/exceptions.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/yacc.prf \
		../../../../Qt/Static/5.13.0_Static/mkspecs/features/lex.prf \
		Daigaku.pro \
		../../../../Qt/Static/5.13.0_Static/plugins/platforms/qwindows.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qgif.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qicns.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qico.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qjpeg.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qtga.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qtiff.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qwbmp.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qwebp.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_debugger.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_inspector.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_local.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_messages.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_native.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_nativedebugger.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_preview.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_profiler.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_quickprofiler.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_server.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_tcp.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/bearer/qgenericbearer.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/sqldrivers/qsqlite.prl \
		../../../../Qt/Static/5.13.0_Static/plugins/sqldrivers/qsqlodbc.prl \
		../../../../Qt/Static/5.13.0_Static/lib/Qt5Quick.prl \
		../../../../Qt/Static/5.13.0_Static/lib/Qt5Gui.prl \
		../../../../Qt/Static/5.13.0_Static/lib/Qt5Qml.prl \
		../../../../Qt/Static/5.13.0_Static/lib/Qt5Network.prl \
		../../../../Qt/Static/5.13.0_Static/lib/Qt5Sql.prl \
		../../../../Qt/Static/5.13.0_Static/lib/Qt5Core.prl \
		../../../../Qt/Static/5.13.0_Static/qml/QtQuick.2/qtquick2plugin.prl \
		../../../../Qt/Static/5.13.0_Static/qml/QtQuick/Window.2/windowplugin.prl \
		../../../../Qt/Static/5.13.0_Static/lib/qtmain.prl
	$(QMAKE) -o Makefile Daigaku.pro -spec win32-g++ "CONFIG+=release" "CONFIG+=qtquickcompiler"
../../../../Qt/Static/5.13.0_Static/mkspecs/features/spec_pre.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/qdevice.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/device_config.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/sanitize.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/gcc-base.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/g++-base.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/angle.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/windows-vulkan.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/g++-win32.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/common/windows-desktop.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/qconfig.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axbase.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axserver.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_winextras.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_dsengine.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qdirect2d.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qgif.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qicns.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qico.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsqlodbc.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsvg.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtexttospeech_sapi.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtga.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtiff.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qttinycanbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwebgl.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwebp.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwindows.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_scene2d.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/modules/qt_plugin_xinputgamepad.pri:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/qt_functions.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/qt_config.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/win32-g++/qmake.conf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/exclusive_builds.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/toolchain.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/default_pre.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/default_pre.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/resolve_config.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/default_post.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/resources.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/qtquickcompiler.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/precompile_header.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/warn_on.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/qt.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/gc_binaries.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/moc.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/opengl.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/qmake_use.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/file_copies.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/win32/windows.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/testcase_targets.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/exceptions.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/yacc.prf:
../../../../Qt/Static/5.13.0_Static/mkspecs/features/lex.prf:
Daigaku.pro:
../../../../Qt/Static/5.13.0_Static/plugins/platforms/qwindows.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qgif.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qicns.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qico.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qjpeg.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qtga.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qtiff.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qwbmp.prl:
../../../../Qt/Static/5.13.0_Static/plugins/imageformats/qwebp.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_debugger.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_inspector.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_local.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_messages.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_native.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_nativedebugger.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_preview.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_profiler.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_quickprofiler.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_server.prl:
../../../../Qt/Static/5.13.0_Static/plugins/qmltooling/qmldbg_tcp.prl:
../../../../Qt/Static/5.13.0_Static/plugins/bearer/qgenericbearer.prl:
../../../../Qt/Static/5.13.0_Static/plugins/sqldrivers/qsqlite.prl:
../../../../Qt/Static/5.13.0_Static/plugins/sqldrivers/qsqlodbc.prl:
../../../../Qt/Static/5.13.0_Static/lib/Qt5Quick.prl:
../../../../Qt/Static/5.13.0_Static/lib/Qt5Gui.prl:
../../../../Qt/Static/5.13.0_Static/lib/Qt5Qml.prl:
../../../../Qt/Static/5.13.0_Static/lib/Qt5Network.prl:
../../../../Qt/Static/5.13.0_Static/lib/Qt5Sql.prl:
../../../../Qt/Static/5.13.0_Static/lib/Qt5Core.prl:
../../../../Qt/Static/5.13.0_Static/qml/QtQuick.2/qtquick2plugin.prl:
../../../../Qt/Static/5.13.0_Static/qml/QtQuick/Window.2/windowplugin.prl:
../../../../Qt/Static/5.13.0_Static/lib/qtmain.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Daigaku.pro -spec win32-g++ "CONFIG+=release" "CONFIG+=qtquickcompiler"

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\79788\Documents\Daigaku\daigaku_plugin_import.cpp C:\Users\79788\Documents\Daigaku\daigaku_qml_plugin_import.cpp .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
